In [16]:
import numpy as np
nums = np.array(range(1, 11), copy=True)
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
ones = np.ones([2, 4], dtype=np.float64)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
zeros = np.zeros([2, 4], dtype=np.float64)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
empty = np.empty([2, 4], dtype=np.float64)
empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
nums.ndim

1

In [21]:
ones.shape

(2, 4)

In [22]:
zeros.dtype

dtype('float64')

eye(N, M=None, k=0, dtype=np.float) 함수는 NxM 단위 행렬을 만든다. k번째 대각선이 1이고 나머지는 0이다. k가 양수이면 주대각선 위로 대각선을 그린다. M을 기본 값(None)으로 지정하면 N과 같다.

In [24]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [28]:
steps = np.arange(2, 5, 0.25)
steps

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])

In [29]:
steps.astype(np.int)

array([2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [31]:
steps_new = steps.copy()
steps_new

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])